version: "3.3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    network_mode: webnet
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qysg18xxjs
    volumes:
      - "./mongodb/data:/data/db"
      - "./mongodb/config:/data/configdb"
    command: mongod --auth # 启动授权登录
