version: "3.3"
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: ${ip_address}.4
    restart: always
    networks:
      default:
        ipv4_address: ${ip_address}.4

networks:
  default:
    external:
      name: webnet

