version: "3.3"
services:
  registers:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    container_name: registers
    restart: always
    network_mode: webnet
    ports:
      - "8080:8080"
    volumes:
      - "./tomcat/apps/register:/usr/local/tomcat/webapps"
      - "./tomcat/logs/register:/usr/local/tomcat/logs"
    environment:
      EUREKA_SERVER_HOST: 192.168.1.6
      EUREKA_SERVER_PORT: 8080
      EUREKA_INSTANCE_IP: 192.168.1.6
      KAFKA_HOST: 192.168.1.6
      KAFKA_PORT: 9092

  authorizers:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    container_name: authorizers
    network_mode: webnet
    ports:
      - "7071:8080"
    environment:
      DATABASE_HOST: 192.168.1.6
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: lhbwyp_ems
      EUREKA_SERVER_HOST: 192.168.1.6
      EUREKA_SERVER_PORT: 8080
      EUREKA_INSTANCE_IP: 192.168.1.6
      REDIS_HOST: 192.168.1.6
      REDIS_PORT: 6379
      KAFKA_HOST: 192.168.1.6
      KAFKA_PORT: 9092
    external_links:
      - redis
      - kafka
      - registers
    volumes:
      - "./tomcat/apps/authorizer:/usr/local/tomcat/webapps"
      - "./tomcat/logs/authorizer:/usr/local/tomcat/logs"
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: "sh /wait-for-it.sh -t 65 registers:8080 -- catalina.sh run"

  qysgs:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    container_name: qysgs
    network_mode: webnet
    ports:
      - "7073:8080"
    environment:
      DATABASE_HOST: 192.168.1.6
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: lhbwyp_ems
      EUREKA_SERVER_HOST: 192.168.1.6
      EUREKA_SERVER_PORT: 8080
      EUREKA_INSTANCE_IP: 192.168.1.6
      REDIS_HOST: 192.168.1.6
      REDIS_PORT: 6379
      REDIS_PASSWORD: lhbwypems1324
      KAFKA_HOST: 192.168.1.6
      KAFKA_PORT: 9092
      QUARTZ_DATABASE_HOST: 192.168.1.6
      QUARTZ_DATABASE_PORT: 3306
      QUARTZ_DATABASE_USER: root
      QUARTZ_DATABASE_PASSWORD: lhbwypems1324
    volumes:
      - "./tomcat/apps/qysg:/usr/local/tomcat/webapps"
      - "./tomcat/logs/qysg:/usr/local/tomcat/logs"
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: "sh /wait-for-it.sh -t 65 registers:8080 -- catalina.sh run"

  timebanks:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    container_name: timebanks
    network_mode: webnet
    ports:
      - "7075:8080"
    environment:
      DATABASE_HOST: 192.168.1.6
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: lhbwyp_ems
      EUREKA_SERVER_HOST: 192.168.1.6
      EUREKA_SERVER_PORT: 8080
      EUREKA_INSTANCE_IP: 192.168.1.6
      REDIS_HOST: 192.168.1.6
      REDIS_PORT: 6379
      KAFKA_HOST: 192.168.1.6
      KAFKA_PORT: 9092
      QUARTZ_DATABASE_HOST: 192.168.1.6
      QUARTZ_DATABASE_PORT: 3306
      QUARTZ_DATABASE_USER: root
      QUARTZ_DATABASE_PASSWORD: lhbwypems1324
    volumes:
      - "./tomcat/apps/timebank:/usr/local/tomcat/webapps"
      - "./tomcat/logs/timebank:/usr/local/tomcat/logs"
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: "sh /wait-for-it.sh -t 65 registers:8080 -- catalina.sh run"


