version: "3.3"
services:
  nexus: 
    restart: always 
    image: sonatype/nexus3 
    container_name: nexus
    network_mode: host
    ports:
      - 8081:8081
    volumes:
      - "./nexus/data:/nexus-data"

