version: "3.3"
services:
  redis: 
    image: redis
    container_name: redis
    hostname: ${ip_address}.10
    restart: always
    command: redis-server --requirepass lhbwypems1324 --appendonly yes
    networks:
      default:
        ipv4_address: ${ip_address}.10
    volumes:
      - "./redis/data:/data"
#      - "./redis/redis.conf:/etc/redis/redis.conf"

networks:
  default:
    external:
      name: webnet

