version: "3.3"
services:
  auths1:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    container_name: auths1
    network_mode: webnet
    ports:
      - "7071:8080"
    environment:
      DATABASE_HOST: 192.168.1.6
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: lhbwyp_ems
      EUREKA_SERVER_HOST: 192.168.1.6
      EUREKA_SERVER_PORT: 8080
      EUREKA_INSTANCE_IP: 192.168.1.6
      REDIS_HOST: 192.168.1.6
      REDIS_PORT: 6379
      KAFKA_HOST: 192.168.1.6
      KAFKA_PORT: 9092
    external_links:
      - redis
      - kafka
      - registers
    volumes:
      - "./tomcat/apps/authorizer1:/usr/local/tomcat/webapps"
      - "./tomcat/logs/authorizer1:/usr/local/tomcat/logs"
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: "sh /wait-for-it.sh registers:8080 -- catalina.sh run"


