version: "3.3"
services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    network_mode: zabbixnet
    ports:
      - "4306:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      # '--lower_case_table_names=1'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: lhbwyp_ems
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123456
      MYSQL_DATABASE: zabbix
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"

  zabbix_server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix_server
    restart: always
    network_mode: zabbixnet
    ports: 
      - "10051:10051"
    environment:
      DB_SERVER_HOST: mysql57
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123456
      MYSQL_DATABASE: zabbix

  zabbix_web: 
    image: zabbix/zabbix-web-apache-mysql
    container_name: zabbix_web
    restart: always
    network_mode: zabbixnet
    ports:
      - "8088:80"
    environment:
      DB_SERVER_HOST: mysql57
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123456
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix_server
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Asia/Shanghai

