version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    restart: always
    network_mode: webnet
    ports:
      - "2181:2181"
 
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    network_mode: webnet
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: "sh /wait-for-it.sh zookeeper:2181 -- docker-entrypoint.sh"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.6
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafkamanager:
    image: sheepkiller/kafka-manager
    container_name: kafkamanager
    restart: always
    network_mode: webnet
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    depends_on:
      - kafka
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: "sh /wait-for-it.sh kafka:9092 -- docker-entrypoint.sh"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true

  redis: 
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass lhbwypems1324 --appendonly yes
    network_mode: webnet
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
#      - "./redis/redis.conf:/etc/redis/redis.conf"

  registers:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    container_name: registers
    restart: always
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
      - redis
    volumes:
      - "./tomcat/apps/register:/usr/local/tomcat/webapps"
      - "./tomcat/logs/register:/usr/local/tomcat/logs"

#networks:
#  mainnet:
#    driver: bridge
#    enable_ipv6: true
#    ipam:
#      driver: default
#      config:
#        -
#          subnet: 10.0.0.0/24

