version: "3.3"
services:
  ethereum:
    image: ethereum/client-go
    container_name: ethereum
    restart: always
    network_mode: zabbixnet
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - "./ethereum:/root/ethereum"

