version: "3.3"
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: ${ip_address}.4
    restart: always
    networks:
      default:
        ipv4_address: ${ip_address}.4
 
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    hostname: ${ip_address}.5
    restart: always
    networks:
      default:
        ipv4_address: ${ip_address}.5
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/logs1:/kafka
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${ip_address}.5:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_BROKER_ID: 1
      KAFKA_HOST_NAME: kafka1
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9999

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    hostname: ${ip_address}.6
    restart: always
    networks:
      default:
        ipv4_address: ${ip_address}.6
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/logs2:/kafka
    environment:
      KAFKA_HOST_NAME: kafka2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${ip_address}.6:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_BROKER_ID: 2
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9999

  kafkamanager:
    image: hlebalbau/kafka-manager
    container_name: kafkamanager
    hostname: ${ip_address}.8
    restart: always
    networks:
      default:
        ipv4_address: ${ip_address}.8
    links:
      - zookeeper
      - kafka1
      - kafka2
    depends_on:
      - kafka1
      - kafka2
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_BROKERS: kafka1:9092,kafka2:9092
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: "root"
      KAFKA_MANAGER_PASSWORD: "qysg18xxjs"
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    volumes:
      - ./kafka/manager/conf:/kafka-manager/conf
      - ./kafka/manager/logs:/kafka-manager/logs

networks:
  default:
    external:
      name: webnet

