version: "3.3"
services:
  nexus:
    restart: always
    image: sonatype/nexus3
    hostname: ${ip_address}.2
    container_name: nexus
    networks:
      default:
        ipv4_address: ${ip_address}.2
    volumes:
      - "./nexus/data:/nexus-data"

  nginx:
    image: nginx
    container_name: nginx
    hostname: ${ip_address}.3
    restart: always
    networks:
      default:
        ipv4_address: ${ip_address}.3
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/www:/usr/share/nginx/html"
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    environment:
      - TZ=Asia/Shanghai

networks:
  default:
    external:
      name: webnet

