version: "3.3"
services:
  qysgs1:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    container_name: qysgs1
    network_mode: webnet
    ports:
      - "6063:8080"
    environment:
      DATABASE_HOST: 192.168.1.6
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: lhbwyp_ems
      EUREKA_SERVER_HOST: 192.168.1.6
      EUREKA_SERVER_PORT: 8080
      EUREKA_INSTANCE_IP: 192.168.1.6
      REDIS_HOST: 192.168.1.6
      REDIS_PORT: 6379
      KAFKA_HOST: 192.168.1.6
      KAFKA_PORT: 9092
      QUARTZ_DATABASE_HOST: 192.168.1.6
      QUARTZ_DATABASE_PORT: 3306
      QUARTZ_DATABASE_USER: root
      QUARTZ_DATABASE_PASSWORD: lhbwypems1324
    volumes:
      - "./tomcat/apps/qysg1:/usr/local/tomcat/webapps"
      - "./tomcat/logs/qysg1:/usr/local/tomcat/logs"

