version: "3.7"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    hostname: ${ip_address}.100
    environment:
      - TZ=Asia/Shanghai
#   ports:
#     - '3083:8080'
#     - '50001:50000'
    volumes:
      - ./jenkins/data:/var/jenkins_home:z
#      - ./jenkins/data/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: ${ip_address}.100

networks:
  default:
    external:
      name: webnet

